project_name: pyscn

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: pyscn
    main: ./cmd/pyscn
    binary: pyscn
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: pyscn
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 'Other'
      order: 999

release:
  github:
    owner: ludo-technologies
    name: pyscn
  draft: false
  prerelease: auto
  mode: append
  name_template: "{{.ProjectName}}-v{{.Version}}"
  
  footer: |
    ## Installation
    
    ### macOS/Linux
    ```bash
    curl -sSfL https://github.com/ludo-technologies/pyscn/releases/download/v{{.Version}}/pyscn_$(uname -s)_$(uname -m).tar.gz | tar xz
    sudo mv pyscn /usr/local/bin/
    ```
    
    ### Go Install
    ```bash
    go install github.com/ludo-technologies/pyscn/cmd/pyscn@v{{.Version}}
    ```