# pyscn MCP Server Configuration

[server]
name = "pyscn"
version = "1.0.0"
description = "Python Code Quality Analyzer - MCP Server"

# Transport configuration
[transport]
# Supported types: "stdio", "sse", "websocket"
type = "stdio"

# SSE transport configuration (when type = "sse")
[sse]
host = "localhost"
port = 8080
endpoint = "/message"

# WebSocket transport configuration (when type = "websocket")
[websocket]
host = "localhost"
port = 8081

# Default analysis configurations
[defaults]
recursive = true
min_complexity = 1
max_complexity = 0
similarity_threshold = 0.8
min_lines = 5
group_clones = true

# Performance settings
[performance]
timeout_seconds = 300
max_concurrent_analyses = 4

# Logging
[logging]
level = "info"  # debug, info, warn, error
file = ""       # empty = stdout only
