[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyscn-mcp"
dynamic = ["version"]
description = "MCP (Model Context Protocol) server for pyscn Python code analyzer"
readme = "README-mcp.md"
authors = [
    {name = "DaisukeYoda", email = "daisukeyoda@users.noreply.github.com"}
]
maintainers = [
    {name = "DaisukeYoda", email = "daisukeyoda@users.noreply.github.com"}
]
keywords = [
    "mcp",
    "model-context-protocol",
    "pyscn",
    "python",
    "static-analysis",
    "code-quality"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Quality Assurance",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = []

[project.scripts]
pyscn-mcp = "pyscn_mcp.__main__:main"

[project.urls]
Homepage = "https://github.com/ludo-technologies/pyscn"
Documentation = "https://github.com/ludo-technologies/pyscn/tree/main/docs"
Repository = "https://github.com/ludo-technologies/pyscn"
Issues = "https://github.com/ludo-technologies/pyscn/issues"
Changelog = "https://github.com/ludo-technologies/pyscn/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = ["pyscn_mcp"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
pyscn_mcp = ["bin/*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.py[co]", "__pycache__", "*.so", "*.pyd"]

[tool.setuptools_scm]
root = ".."
