name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Zig as C/C++ cross-compiler
        CC_linux_amd64: "zig cc -target x86_64-linux"
        CXX_linux_amd64: "zig c++ -target x86_64-linux"
        CC_linux_arm64: "zig cc -target aarch64-linux"
        CXX_linux_arm64: "zig c++ -target aarch64-linux"
        CC_darwin_amd64: "zig cc -target x86_64-macos"
        CXX_darwin_amd64: "zig c++ -target x86_64-macos"
        CC_darwin_arm64: "zig cc -target aarch64-macos"
        CXX_darwin_arm64: "zig c++ -target aarch64-macos"
        CC_windows_amd64: "zig cc -target x86_64-windows"
        CXX_windows_amd64: "zig c++ -target x86_64-windows"
        CC_windows_arm64: "zig cc -target aarch64-windows"
        CXX_windows_arm64: "zig c++ -target aarch64-windows"
